### ISSUE TITLE
Add year to log

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/benchmark-tools#25]
### Please describe the feature you'd like

The log report the time but its missing the year

```
I0108 23:55:00.237840   68036 main.go:187]  Starting goroutine 581 of 693 1F51_center-of-mass
I0108 23:59:10.359445   68036 main.go:187]  Starting goroutine 582 of 693 1F51_random-restraints
I0109 00:07:53.937045   68036 main.go:187]  Starting goroutine 583 of 693 1FC2_true-interface
I0109 00:15:56.500863   68036 main.go:187]  Starting goroutine 584 of 693 1FC2_center-of-mass
```

### Why is it relevant?

It would make easier to figure out how for how long each routine took to run

**Comment by rvhonorato** [comment]
Seems like the `glog` lib is missing the year assignment, so the format is 

`Lmmdd hh:mm:ss.uuuuuu threadid file:line]`, which should be fine

https://github.com/golang/glog/blob/9ef845f417d839250ceabbc25c1b26101e772dd7/glog.go#L562-L564

**Comment by amjjbonvin** [comment]
Do we really need the uuuuu part?

**Comment by rvhonorato** [comment]
I think so, given how fast and multi-threaded it is, its useful to know what/if something is going wrong and in which order/thread.
