### ISSUE TITLE
Suggest closely related parameter name when a given one is not found

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/benchmark-tools#32]
### Please describe the feature you'd like
We could check the wrong parameter and suggest one that closely matches it. This can be done using some implementation of the Levenshtein distance, there are [some implementations available](https://pkg.go.dev/search?q=Levenshtein)

### Why is it relevant?
Given the huge number of parameters haddock has, if you input a wrong parameter, it might be tricky to figure out what is the correct name. For that you'll need to go back to the documentation/code and find out the correct name.

**Comment by joaomcteixeira** [comment]
@douweschulte implemented it in HADDOCK3 [here](https://github.com/haddocking/haddock3/blob/23f778c1ed94388df6788804724db170681a6cea/src/haddock/gear/prepare_run.py#L850).

**Comment by rvhonorato** [comment]
indeed, best if it's handled directly there
