### ISSUE TITLE
Add support for runs without ligand

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/benchmark-tools#43]
### Please describe the feature you'd like
In HADDOCK3 users can input a single molecule for refinement, but the benchmark-tools expect the configuration to have both receptor and ligands (docking)

### Why is it relevant?
As it is there's no support for "refinement runs"

**Comment by rvhonorato** [comment]
Does this also apply to HADDOCK2+ @amjjbonvin? aka, can you prepare a run using only one `PDB_FILE` in `run.param`?

**Comment by amjjbonvin** [comment]
Yes you can
